// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkS2A7-GLmDcS5KAkOx6ysVfGvjt2x-y0',
    appId: '1:476803789576:web:4c7bdc9ff279306a81b2bd',
    messagingSenderId: '476803789576',
    projectId: 'familyflow-576e1',
    authDomain: 'familyflow-576e1.firebaseapp.com',
    storageBucket: 'familyflow-576e1.firebasestorage.app',
    measurementId: 'G-CMLXJK3YEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRvlOqQWHjMcEPwXSfDknn_g7ABWcVLvE',
    appId: '1:476803789576:android:59b944b8850552c881b2bd',
    messagingSenderId: '476803789576',
    projectId: 'familyflow-576e1',
    storageBucket: 'familyflow-576e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiTRCZX89-SSVI_lclAaVB0tx3Bi7X-NE',
    appId: '1:476803789576:ios:8d143088f10bcb5581b2bd',
    messagingSenderId: '476803789576',
    projectId: 'familyflow-576e1',
    storageBucket: 'familyflow-576e1.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiTRCZX89-SSVI_lclAaVB0tx3Bi7X-NE',
    appId: '1:476803789576:ios:8d143088f10bcb5581b2bd',
    messagingSenderId: '476803789576',
    projectId: 'familyflow-576e1',
    storageBucket: 'familyflow-576e1.firebasestorage.app',
    iosBundleId: 'com.example.lifeOs',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkS2A7-GLmDcS5KAkOx6ysVfGvjt2x-y0',
    appId: '1:476803789576:web:28d02da933cdd90581b2bd',
    messagingSenderId: '476803789576',
    projectId: 'familyflow-576e1',
    authDomain: 'familyflow-576e1.firebaseapp.com',
    storageBucket: 'familyflow-576e1.firebasestorage.app',
    measurementId: 'G-E46DE5QWP6',
  );

}